# Generated by Django 5.2.6 on 2026-02-06 14:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('event_payload', models.JSONField()),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_version', models.PositiveIntegerField()),
                ('trace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['processed_at', 'created_at'], name='outbox_polling_idx')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_id', 'aggregate_version'), name='unique_aggregate_version')],
            },
        ),
    ]
