[pytest]
DJANGO_SETTINGS_MODULE = wallet_service.settings
addopts = --reuse-db
pythonpath = .
testpaths = 
    tests

# Match test files in all subdirectories of 'tests/'
python_files = 
    test_*.py
    *_test.py
    *_tests.py
    tests.py

# Optionally, also include classes and functions (if needed)
python_classes = Test* *Test
python_functions = test_*