apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kafka }}
  labels:
    app: kafka
    app.kubernetes.io/component: message-broker
type: Opaque
stringData:
  KAFKA_CLIENT_ID: "wallet-service"
  # Add SASL credentials here if you enable authentication later
  # KAFKA_SASL_USERNAME: {{ .Values.config.wallet.kafkaUser | quote }}
  # KAFKA_SASL_PASSWORD: {{ .Values.config.wallet.kafkaPass | quote }}