apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kafka }}
  labels:
    app: kafka
    app.kubernetes.io/component: message-broker
type: Opaque
stringData:
  # Auth service Kafka
  AUTH_KAFKA_CLIENT_ID: auth-service
  # Payment service Kafka
  PAYMENT_KAFKA_CLIENT_ID: payment-service
  # Booking service Kafka
  BOOKING_KAFKA_CLIENT_ID: booking-service
  # Wallet service Kafka
  WALLET_KAFKA_CLIENT_ID: wallet-service
  # Room service Kafka
  ROOM_KAFKA_CLIENT_ID: room-service