apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres }}
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.data.postgres.user | default "ishimwe" | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.data.postgres.password | default "2025New+" | quote }}
  # Wallet service database
  DB_NAME: {{ .Values.config.wallet.postgresDb | default "walletdb" | quote }}
  DB_USER: {{ .Values.secrets.data.postgres.user | default "ishimwe" | quote }}
  DB_PASSWORD: {{ .Values.secrets.data.postgres.password | default "2025New+" | quote }}