apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres }}
  labels:
    app: postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.config.wallet.postgresUser | default "ishimwe" | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.wallet.postgresPassword | default "2025New+" | quote }}
  POSTGRES_DB: {{ .Values.config.wallet.postgresDb | default "walletdb" | quote }}