apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rabbitmq }}
  labels:
    app: rabbitmq
    app.kubernetes.io/component: message-broker
type: Opaque
stringData:
  RABBITMQ_USER: {{ .Values.secrets.data.rabbitmq.user | default "ishimwe" | quote }}
  RABBITMQ_PASS: {{ .Values.secrets.data.rabbitmq.pass | default "GA4xdr2K1hbUdJgB1DOJXsUOq0WK6koXZy3M9ATy7Ec=" | quote }}
  RABBITMQ_DEFAULT_VHOST: {{ .Values.config.wallet.rabbitmqVhost | default "microservice_one" | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.secrets.data.rabbitmq.erlangCookie | default "secure-cookie-for-cluster" | quote }}
  # Auth service RabbitMQ
  AUTH_RABBITMQ_USER: {{ .Values.secrets.data.rabbitmq.user | default "ishimwe" | quote }}
  AUTH_RABBITMQ_PASS: {{ .Values.secrets.data.rabbitmq.pass | default "GA4xdr2K1hbUdJgB1DOJXsUOq0WK6koXZy3M9ATy7Ec=" | quote }}
  # Payment service RabbitMQ
  PAYMENT_RABBITMQ_USER: {{ .Values.secrets.data.rabbitmq.user | default "ishimwe" | quote }}
  PAYMENT_RABBITMQ_PASS: {{ .Values.secrets.data.rabbitmq.pass | default "GA4xdr2K1hbUdJgB1DOJXsUOq0WK6koXZy3M9ATy7Ec=" | quote }}
  # Booking service RabbitMQ
  BOOKING_RABBITMQ_USER: {{ .Values.secrets.data.rabbitmq.user | default "ishimwe" | quote }}
  BOOKING_RABBITMQ_PASS: {{ .Values.secrets.data.rabbitmq.pass | default "GA4xdr2K1hbUdJgB1DOJXsUOq0WK6koXZy3M9ATy7Ec=" | quote }}
  # Wallet service RabbitMQ
  WALLET_RABBITMQ_USER: {{ .Values.secrets.data.rabbitmq.user | default "ishimwe" | quote }}
  WALLET_RABBITMQ_PASS: {{ .Values.secrets.data.rabbitmq.pass | default "GA4xdr2K1hbUdJgB1DOJXsUOq0WK6koXZy3M9ATy7Ec=" | quote }}
  # Room service RabbitMQ
  ROOM_RABBITMQ_USER: {{ .Values.secrets.data.rabbitmq.user | default "ishimwe" | quote }}
  ROOM_RABBITMQ_PASS: {{ .Values.secrets.data.rabbitmq.pass | default "GA4xdr2K1hbUdJgB1DOJXsUOq0WK6koXZy3M9ATy7Ec=" | quote }}