apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rabbitmq }}
  labels:
    app: rabbitmq
    app.kubernetes.io/component: message-broker
type: Opaque
stringData:
  RABBITMQ_USER: {{ .Values.config.wallet.rabbitmqUser | default "ishimwe" | quote }}
  RABBITMQ_PASS: {{ .Values.config.wallet.rabbitmqPass | default "GA4xdr2K1hbUdJgB1DOJXsUOq0WK6koXZy3M9ATy7Ec=" | quote }}
  RABBITMQ_DEFAULT_VHOST: {{ .Values.config.wallet.rabbitmqVhost | default "microservice_one" | quote }}