apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.redis }}
  labels:
    app: redis
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.secrets.data.redis.password | default "dev-redis-password" | quote }}