apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.wallet }}
  labels:
    app: wallet
    app.kubernetes.io/component: wallet-service
type: Opaque
stringData:
  # Django
  DJANGO_SECRET_KEY: {{ .Values.secrets.data.wallet.djangoSecretKey | default "django-insecure-$mlx&v1w@t&d#=c@k76%c9qp+2frp*i_q&7cdj!wiuey90$e0y" | quote }}
  DJANGO_DEBUG: {{ .Values.config.wallet.djangoDebug | default "False" | quote }}
  
  # Auth & Security
  INTERNAL_API_KEY: {{ .Values.secrets.data.wallet.internalApiKey | default "super-secret-internal-key-change-in-prod" | quote }}
  SERVICE_JWT: {{ .Values.secrets.data.wallet.serviceJwt | default "my_jwt_secret_123!" | quote }}
  JWT_SECRET: {{ .Values.secrets.data.wallet.jwtSecret | default "my_jwt_secret_123!" | quote }}