apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.appname" (dict "ctx" $ "svc" "wallet") }}
  labels:
    app: {{ include "helm.appname" (dict "ctx" $ "svc" "wallet") }}
    app.kubernetes.io/component: wallet-service
type: Opaque
stringData:
  # Django
  DJANGO_SECRET_KEY: {{ .Values.config.wallet.djangoSecretKey | default "django-insecure-change-me-in-prod" | quote }}

  # Auth & Security
  INTERNAL_API_KEY: {{ .Values.config.wallet.internalApiKey | default "change-me" | quote }}
  SERVICE_JWT: {{ .Values.config.wallet.serviceJwt | default "change-me" | quote }}
  JWT_SECRET: {{ .Values.config.wallet.jwtSecret | default "change-me" | quote }}
  
  # Database (if not already in postgres secret)
  POSTGRES_USER: {{ .Values.config.wallet.postgresUser | default "ishimwe" | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.wallet.postgresPassword | default "2025New+" | quote }}