# Generated by Django 5.2.6 on 2026-02-06 14:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_name', models.CharField(max_length=100, unique=True)),
                ('last_event_id', models.UUIDField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projection_state',
            },
        ),
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_version', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=255)),
                ('event_payload', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'event_store',
                'ordering': ['aggregate_version'],
                'indexes': [models.Index(fields=['aggregate_id', 'aggregate_type'], name='event_store_aggrega_f1fd7b_idx'), models.Index(fields=['created_at'], name='event_store_created_7c4c1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_id', 'aggregate_version'), name='unique_aggregate_event_version')],
            },
        ),
    ]
