# Generated by Django 5.2.6 on 2026-02-06 14:55

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletReadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique wallet identifier', primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='UUID of the user owning the wallet', verbose_name='user ID')),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=24)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR) in uppercase', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('closed', 'closed')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'wallet read model',
                'verbose_name_plural': 'wallet read models',
                'db_table': 'wallet_read_model',
                'indexes': [models.Index(fields=['user_id'], name='idx_wallet_read_user'), models.Index(fields=['status'], name='idx_wallet_read_status'), models.Index(fields=['currency'], name='idx_wallet_read_currency'), models.Index(fields=['created_at'], name='idx_wallet_read_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', Decimal('0'))), name='check_wallet_balance_non_negative')],
            },
        ),
    ]
